### ISSUE TITLE
Can 2ls work on a real world project?

### ISSUE THREAD

**Issue by ConfZ** [diffblue/2ls#174]
Hi, we are ready to make a testing on a real world project by some tools. Could you please give me some advise to make 2ls work on a project? Thanks!

**Comment by peterschrammel** [comment]
2LS uses the same infrastructure as CBMC. So, you can use [goto-cc](https://diffblue.github.io/cbmc/group__goto-cc.html) for compiling and linking the project into goto-binaries (CBMC's intermediate language).

2LS has similar restrictions wrt scalability as other model checkers. It's more likely to be successful for unit verification (cf. unit testing) rather than running it on the program's entry point.
2LS has lots of options for various types of analyses and degrees of precision.

What kind of properties do you want to check?

**Comment by ConfZ** [comment]
> 2LS uses the same infrastructure as CBMC. So, you can use [goto-cc](https://diffblue.github.io/cbmc/group__goto-cc.html) for compiling and linking the project into goto-binaries (CBMC's intermediate language).
> 
> 2LS has similar restrictions wrt scalability as other model checkers. It's more likely to be successful for unit verification (cf. unit testing) rather than running it on the program's entry point. 2LS has lots of options for various types of analyses and degrees of precision.
> 
> What kind of properties do you want to check?

I'd like to check the non-termination of a project since they could exist infinite loops or recursions. While these projects are consisted of 20 - 50 files rather than a single file, and I am not sure if 2LS can work. Your advise seems to be helpful. Thanks!
